run: test
	java -classpath .:build RunEdgeConvert
test: complie
	java -cp .:lib/junit-4.12.jar:lib/hamcrest-core-1.3.jar:build org.junit.runner.JUnitCore EdgeConnectorTest
complie:
	javac -classpath .:lib/junit-4.12.jar:lib/hamcrest-core-1.3.jar src/main/java/*.java src/test/java/*.java -d build
clean: 
	rm -f *.class
	find . -name \*.class -exec rm {} \;